
export interface HljsStyleTypes {


    "base16/3024": string
    "base16/apathy": string
    "base16/apprentice": string
    "base16/ashes": string
    "base16/atelier-cave": string
    "base16/atelier-cave-light": string
    "base16/atelier-dune": string
    "base16/atelier-dune-light": string
    "base16/atelier-estuary": string
    "base16/atelier-estuary-light": string
    "base16/atelier-forest": string
    "base16/atelier-forest-light": string
    "base16/atelier-heath": string
    "base16/atelier-heath-light": string
    "base16/atelier-lakeside": string
    "base16/atelier-lakeside-light": string
    "base16/atelier-plateau": string
    "base16/atelier-plateau-light": string
    "base16/atelier-savanna": string
    "base16/atelier-savanna-light": string
    "base16/atelier-seaside": string
    "base16/atelier-seaside-light": string
    "base16/atelier-sulphurpool": string
    "base16/atelier-sulphurpool-light": string
    "base16/atlas": string
    "base16/bespin": string
    "base16/black-metal": string
    "base16/black-metal-bathory": string
    "base16/black-metal-burzum": string
    "base16/black-metal-dark-funeral": string
    "base16/black-metal-gorgoroth": string
    "base16/black-metal-immortal": string
    "base16/black-metal-khold": string
    "base16/black-metal-marduk": string
    "base16/black-metal-mayhem": string
    "base16/black-metal-nile": string
    "base16/black-metal-venom": string
    "base16/brewer": string
    "base16/bright": string
    "base16/brogrammer": string
    "base16/brush-trees": string
    "base16/brush-trees-dark": string
    "base16/chalk": string
    "base16/circus": string
    "base16/classic-dark": string
    "base16/classic-light": string
    "base16/codeschool": string
    "base16/colors": string
    "base16/cupcake": string
    "base16/cupertino": string
    "base16/danqing": string
    "base16/darcula": string
    "base16/dark-violet": string
    "base16/darkmoss": string
    "base16/darktooth": string
    "base16/decaf": string
    "base16/default-dark": string
    "base16/default-light": string
    "base16/dirtysea": string
    "base16/dracula": string
    "base16/edge-dark": string
    "base16/edge-light": string
    "base16/eighties": string
    "base16/embers": string
    "base16/equilibrium-dark": string
    "base16/equilibrium-gray-dark": string
    "base16/equilibrium-gray-light": string
    "base16/equilibrium-light": string
    "base16/espresso": string
    "base16/eva": string
    "base16/eva-dim": string
    "base16/flat": string
    "base16/framer": string
    "base16/fruit-soda": string
    "base16/gigavolt": string
    "base16/github": string
    "base16/google-dark": string
    "base16/google-light": string
    "base16/grayscale-dark": string
    "base16/grayscale-light": string
    "base16/green-screen": string
    "base16/gruvbox-dark-hard": string
    "base16/gruvbox-dark-medium": string
    "base16/gruvbox-dark-pale": string
    "base16/gruvbox-dark-soft": string
    "base16/gruvbox-light-hard": string
    "base16/gruvbox-light-medium": string
    "base16/gruvbox-light-soft": string
    "base16/hardcore": string
    "base16/harmonic16-dark": string
    "base16/harmonic16-light": string
    "base16/heetch-dark": string
    "base16/heetch-light": string
    "base16/helios": string
    "base16/hopscotch": string
    "base16/horizon-dark": string
    "base16/horizon-light": string
    "base16/humanoid-dark": string
    "base16/humanoid-light": string
    "base16/ia-dark": string
    "base16/ia-light": string
    "base16/icy-dark": string
    "base16/ir-black": string
    "base16/isotope": string
    "base16/kimber": string
    "base16/london-tube": string
    "base16/macintosh": string
    "base16/marrakesh": string
    "base16/materia": string
    "base16/material": string
    "base16/material-darker": string
    "base16/material-lighter": string
    "base16/material-palenight": string
    "base16/material-vivid": string
    "base16/mellow-purple": string
    "base16/mexico-light": string
    "base16/mocha": string
    "base16/monokai": string
    "base16/nebula": string
    "base16/nord": string
    "base16/nova": string
    "base16/ocean": string
    "base16/oceanicnext": string
    "base16/one-light": string
    "base16/onedark": string
    "base16/outrun-dark": string
    "base16/papercolor-dark": string
    "base16/papercolor-light": string
    "base16/paraiso": string
    "base16/pasque": string
    "base16/phd": string
    "base16/pico": string
    "base16/pop": string
    "base16/porple": string
    "base16/qualia": string
    "base16/railscasts": string
    "base16/rebecca": string
    "base16/ros-pine": string
    "base16/ros-pine-dawn": string
    "base16/ros-pine-moon": string
    "base16/sagelight": string
    "base16/sandcastle": string
    "base16/seti-ui": string
    "base16/shapeshifter": string
    "base16/silk-dark": string
    "base16/silk-light": string
    "base16/snazzy": string
    "base16/solar-flare": string
    "base16/solar-flare-light": string
    "base16/solarized-dark": string
    "base16/solarized-light": string
    "base16/spacemacs": string
    "base16/summercamp": string
    "base16/summerfruit-dark": string
    "base16/summerfruit-light": string
    "base16/synth-midnight-terminal-dark": string
    "base16/synth-midnight-terminal-light": string
    "base16/tango": string
    "base16/tender": string
    "base16/tomorrow": string
    "base16/tomorrow-night": string
    "base16/twilight": string
    "base16/unikitty-dark": string
    "base16/unikitty-light": string
    "base16/vulcan": string
    "base16/windows-10": string
    "base16/windows-10-light": string
    "base16/windows-95": string
    "base16/windows-95-light": string
    "base16/windows-high-contrast": string
    "base16/windows-high-contrast-light": string
    "base16/windows-nt": string
    "base16/windows-nt-light": string
    "base16/woodland": string
    "base16/xcode-dusk": string
    "base16/zenburn": string


    "a11y-dark": string
    "a11y-light": string
    "agate": string
    "an-old-hope": string
    "androidstudio": string
    "arduino-light": string
    "arta": string
    "ascetic": string
    "atom-one-dark": string
    "atom-one-dark-reasonable": string
    "atom-one-light": string
    "brown-paper": string
    "brown-papersq.png": string
    "codepen-embed": string
    "color-brewer": string
    "dark": string
    "default": string
    "devibeans": string
    "docco": string
    "far": string
    "foundation": string
    "github": string
    "github-dark": string
    "github-dark-dimmed": string
    "gml": string
    "googlecode": string
    "gradient-dark": string
    "gradient-light": string
    "grayscale": string
    "hybrid": string
    "idea": string
    "ir-black": string
    "isbl-editor-dark": string
    "isbl-editor-light": string
    "kimbie-dark": string
    "kimbie-light": string
    "lightfair": string
    "lioshi": string
    "magula": string
    "mono-blue": string
    "monokai": string
    "monokai-sublime": string
    "night-owl": string
    "nnfx-dark": string
    "nnfx-light": string
    "nord": string
    "obsidian": string
    "paraiso-dark": string
    "paraiso-light": string
    "pojoaque.jpg": string
    "pojoaque": string
    "purebasic": string
    "qtcreator-dark": string
    "qtcreator-light": string
    "rainbow": string
    "routeros": string
    "school-book": string
    "shades-of-purple": string
    "srcery": string
    "stackoverflow-dark": string
    "stackoverflow-light": string
    "sunburst": string
    "tomorrow-night-blue": string
    "tomorrow-night-bright": string
    "vs": string
    "vs2015": string
    "xcode": string
    "xt256": string

}



